/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\public\models\lietuvamap.glb 
*/

import { useGLTF } from "@react-three/drei";

export function LietuvaMap(props) {
  const { nodes, materials } = useGLTF("/models/lietuvamap.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["zMy7IMQ2Ps4LmNo7BntXP-transformed"]}
        position={[20.805, 0, 0]}
        scale={[10.21, 1, 7.27]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials["Material.013"]}
        position={[21.282, 0, 0.07]}
        scale={[10.44, 1, 7.32]}
      />
    </group>
  );
}

useGLTF.preload("/models/lietuvamap.glb");
